//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.6413
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IActivosFijosService
{
    
    Activo CargarActivo(string Activo_Codigo, string Serie);
    
    bool ActivoInventariado(int Activo_Codigo, int Parame_PeriodoInventario, int Pardet_PeriodoInventario);
    
    string GuardarInventarioDet(string mUsuario, Inventario mInventario, Activo mActivo, int mCustodio, int mParame_Ubicacion, int mPardet_Ubicacion);
    
    bool IniciarSesion(string mUsuario, string mContrasena);
    
    Inventario[] InventariosActivos();
    
    Caracteristica[] ListaCaracteristicas(int parame_tipo, int pardet_tipo);
    
    Empleado[] ListaEmpleados(string parcial);
    
    Factura[] ListaFacturas(int _proveedor);
    
    Proveedor[] ListaProveedores();
    
    Parametro[] ParametroList(int parame_codigo, int parame_padre, int pardet_padre, string filtro);
    
    Parametro[] ParametroTreeList(int parame_inicio, int pardet_inicio, int parame_fin, bool solo_visibles);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("NetCFSvcUtil", "3.5.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/ActivosFijosServices")]
public partial class Activo
{
    
    private int activo_CodigoField;
    
    private bool activo_CodigoFieldSpecified;
    
    private string activo_CodigoAuxField;
    
    private string activo_CodigoBarraField;
    
    private string activo_DescripcionField;
    
    private System.DateTime activo_FechaBajaField;
    
    private bool activo_FechaBajaFieldSpecified;
    
    private System.DateTime activo_FechaCompraField;
    
    private bool activo_FechaCompraFieldSpecified;
    
    private System.DateTime activo_FechaIngresoField;
    
    private bool activo_FechaIngresoFieldSpecified;
    
    private System.DateTime activo_FechaUsoField;
    
    private bool activo_FechaUsoFieldSpecified;
    
    private string activo_ModeloField;
    
    private string activo_ObservacionField;
    
    private string activo_ResponsableMantenimientoField;
    
    private string activo_SerieField;
    
    private Caracteristica[] caracteristicasField;
    
    private int entida_CustodioField;
    
    private bool entida_CustodioFieldSpecified;
    
    private int entida_ProveedorField;
    
    private bool entida_ProveedorFieldSpecified;
    
    private int factura_CodigoField;
    
    private bool factura_CodigoFieldSpecified;
    
    private int parame_CentroCostoField;
    
    private bool parame_CentroCostoFieldSpecified;
    
    private int parame_ClaseActivoField;
    
    private bool parame_ClaseActivoFieldSpecified;
    
    private int parame_EstadoActivoField;
    
    private bool parame_EstadoActivoFieldSpecified;
    
    private int parame_EstadoDepreciacionField;
    
    private bool parame_EstadoDepreciacionFieldSpecified;
    
    private int parame_MarcaField;
    
    private bool parame_MarcaFieldSpecified;
    
    private int parame_TipoBajaActivoField;
    
    private bool parame_TipoBajaActivoFieldSpecified;
    
    private int pardet_CentroCostoField;
    
    private bool pardet_CentroCostoFieldSpecified;
    
    private int pardet_ClaseActivoField;
    
    private bool pardet_ClaseActivoFieldSpecified;
    
    private int pardet_EstadoActivoField;
    
    private bool pardet_EstadoActivoFieldSpecified;
    
    private int pardet_EstadoDepreciacionField;
    
    private bool pardet_EstadoDepreciacionFieldSpecified;
    
    private int pardet_GrupoField;
    
    private bool pardet_GrupoFieldSpecified;
    
    private int pardet_MarcaField;
    
    private bool pardet_MarcaFieldSpecified;
    
    private int pardet_TipoField;
    
    private bool pardet_TipoFieldSpecified;
    
    private int pardet_TipoBajaActivoField;
    
    private bool pardet_TipoBajaActivoFieldSpecified;
    
    private int pardet_UbicacionField;
    
    private bool pardet_UbicacionFieldSpecified;
    
    private bool esNuevoField;
    
    private bool esNuevoFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public int Activo_Codigo
    {
        get
        {
            return this.activo_CodigoField;
        }
        set
        {
            this.activo_CodigoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool Activo_CodigoSpecified
    {
        get
        {
            return this.activo_CodigoFieldSpecified;
        }
        set
        {
            this.activo_CodigoFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
    public string Activo_CodigoAux
    {
        get
        {
            return this.activo_CodigoAuxField;
        }
        set
        {
            this.activo_CodigoAuxField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
    public string Activo_CodigoBarra
    {
        get
        {
            return this.activo_CodigoBarraField;
        }
        set
        {
            this.activo_CodigoBarraField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
    public string Activo_Descripcion
    {
        get
        {
            return this.activo_DescripcionField;
        }
        set
        {
            this.activo_DescripcionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public System.DateTime Activo_FechaBaja
    {
        get
        {
            return this.activo_FechaBajaField;
        }
        set
        {
            this.activo_FechaBajaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool Activo_FechaBajaSpecified
    {
        get
        {
            return this.activo_FechaBajaFieldSpecified;
        }
        set
        {
            this.activo_FechaBajaFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=5)]
    public System.DateTime Activo_FechaCompra
    {
        get
        {
            return this.activo_FechaCompraField;
        }
        set
        {
            this.activo_FechaCompraField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool Activo_FechaCompraSpecified
    {
        get
        {
            return this.activo_FechaCompraFieldSpecified;
        }
        set
        {
            this.activo_FechaCompraFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=6)]
    public System.DateTime Activo_FechaIngreso
    {
        get
        {
            return this.activo_FechaIngresoField;
        }
        set
        {
            this.activo_FechaIngresoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool Activo_FechaIngresoSpecified
    {
        get
        {
            return this.activo_FechaIngresoFieldSpecified;
        }
        set
        {
            this.activo_FechaIngresoFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=7)]
    public System.DateTime Activo_FechaUso
    {
        get
        {
            return this.activo_FechaUsoField;
        }
        set
        {
            this.activo_FechaUsoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool Activo_FechaUsoSpecified
    {
        get
        {
            return this.activo_FechaUsoFieldSpecified;
        }
        set
        {
            this.activo_FechaUsoFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
    public string Activo_Modelo
    {
        get
        {
            return this.activo_ModeloField;
        }
        set
        {
            this.activo_ModeloField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
    public string Activo_Observacion
    {
        get
        {
            return this.activo_ObservacionField;
        }
        set
        {
            this.activo_ObservacionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
    public string Activo_ResponsableMantenimiento
    {
        get
        {
            return this.activo_ResponsableMantenimientoField;
        }
        set
        {
            this.activo_ResponsableMantenimientoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
    public string Activo_Serie
    {
        get
        {
            return this.activo_SerieField;
        }
        set
        {
            this.activo_SerieField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=12)]
    public Caracteristica[] Caracteristicas
    {
        get
        {
            return this.caracteristicasField;
        }
        set
        {
            this.caracteristicasField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=13)]
    public int Entida_Custodio
    {
        get
        {
            return this.entida_CustodioField;
        }
        set
        {
            this.entida_CustodioField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool Entida_CustodioSpecified
    {
        get
        {
            return this.entida_CustodioFieldSpecified;
        }
        set
        {
            this.entida_CustodioFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=14)]
    public int Entida_Proveedor
    {
        get
        {
            return this.entida_ProveedorField;
        }
        set
        {
            this.entida_ProveedorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool Entida_ProveedorSpecified
    {
        get
        {
            return this.entida_ProveedorFieldSpecified;
        }
        set
        {
            this.entida_ProveedorFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=15)]
    public int Factura_Codigo
    {
        get
        {
            return this.factura_CodigoField;
        }
        set
        {
            this.factura_CodigoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool Factura_CodigoSpecified
    {
        get
        {
            return this.factura_CodigoFieldSpecified;
        }
        set
        {
            this.factura_CodigoFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=16)]
    public int Parame_CentroCosto
    {
        get
        {
            return this.parame_CentroCostoField;
        }
        set
        {
            this.parame_CentroCostoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool Parame_CentroCostoSpecified
    {
        get
        {
            return this.parame_CentroCostoFieldSpecified;
        }
        set
        {
            this.parame_CentroCostoFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=17)]
    public int Parame_ClaseActivo
    {
        get
        {
            return this.parame_ClaseActivoField;
        }
        set
        {
            this.parame_ClaseActivoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool Parame_ClaseActivoSpecified
    {
        get
        {
            return this.parame_ClaseActivoFieldSpecified;
        }
        set
        {
            this.parame_ClaseActivoFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=18)]
    public int Parame_EstadoActivo
    {
        get
        {
            return this.parame_EstadoActivoField;
        }
        set
        {
            this.parame_EstadoActivoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool Parame_EstadoActivoSpecified
    {
        get
        {
            return this.parame_EstadoActivoFieldSpecified;
        }
        set
        {
            this.parame_EstadoActivoFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=19)]
    public int Parame_EstadoDepreciacion
    {
        get
        {
            return this.parame_EstadoDepreciacionField;
        }
        set
        {
            this.parame_EstadoDepreciacionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool Parame_EstadoDepreciacionSpecified
    {
        get
        {
            return this.parame_EstadoDepreciacionFieldSpecified;
        }
        set
        {
            this.parame_EstadoDepreciacionFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=20)]
    public int Parame_Marca
    {
        get
        {
            return this.parame_MarcaField;
        }
        set
        {
            this.parame_MarcaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool Parame_MarcaSpecified
    {
        get
        {
            return this.parame_MarcaFieldSpecified;
        }
        set
        {
            this.parame_MarcaFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=21)]
    public int Parame_TipoBajaActivo
    {
        get
        {
            return this.parame_TipoBajaActivoField;
        }
        set
        {
            this.parame_TipoBajaActivoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool Parame_TipoBajaActivoSpecified
    {
        get
        {
            return this.parame_TipoBajaActivoFieldSpecified;
        }
        set
        {
            this.parame_TipoBajaActivoFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=22)]
    public int Pardet_CentroCosto
    {
        get
        {
            return this.pardet_CentroCostoField;
        }
        set
        {
            this.pardet_CentroCostoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool Pardet_CentroCostoSpecified
    {
        get
        {
            return this.pardet_CentroCostoFieldSpecified;
        }
        set
        {
            this.pardet_CentroCostoFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=23)]
    public int Pardet_ClaseActivo
    {
        get
        {
            return this.pardet_ClaseActivoField;
        }
        set
        {
            this.pardet_ClaseActivoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool Pardet_ClaseActivoSpecified
    {
        get
        {
            return this.pardet_ClaseActivoFieldSpecified;
        }
        set
        {
            this.pardet_ClaseActivoFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=24)]
    public int Pardet_EstadoActivo
    {
        get
        {
            return this.pardet_EstadoActivoField;
        }
        set
        {
            this.pardet_EstadoActivoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool Pardet_EstadoActivoSpecified
    {
        get
        {
            return this.pardet_EstadoActivoFieldSpecified;
        }
        set
        {
            this.pardet_EstadoActivoFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=25)]
    public int Pardet_EstadoDepreciacion
    {
        get
        {
            return this.pardet_EstadoDepreciacionField;
        }
        set
        {
            this.pardet_EstadoDepreciacionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool Pardet_EstadoDepreciacionSpecified
    {
        get
        {
            return this.pardet_EstadoDepreciacionFieldSpecified;
        }
        set
        {
            this.pardet_EstadoDepreciacionFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=26)]
    public int Pardet_Grupo
    {
        get
        {
            return this.pardet_GrupoField;
        }
        set
        {
            this.pardet_GrupoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool Pardet_GrupoSpecified
    {
        get
        {
            return this.pardet_GrupoFieldSpecified;
        }
        set
        {
            this.pardet_GrupoFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=27)]
    public int Pardet_Marca
    {
        get
        {
            return this.pardet_MarcaField;
        }
        set
        {
            this.pardet_MarcaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool Pardet_MarcaSpecified
    {
        get
        {
            return this.pardet_MarcaFieldSpecified;
        }
        set
        {
            this.pardet_MarcaFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=28)]
    public int Pardet_Tipo
    {
        get
        {
            return this.pardet_TipoField;
        }
        set
        {
            this.pardet_TipoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool Pardet_TipoSpecified
    {
        get
        {
            return this.pardet_TipoFieldSpecified;
        }
        set
        {
            this.pardet_TipoFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=29)]
    public int Pardet_TipoBajaActivo
    {
        get
        {
            return this.pardet_TipoBajaActivoField;
        }
        set
        {
            this.pardet_TipoBajaActivoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool Pardet_TipoBajaActivoSpecified
    {
        get
        {
            return this.pardet_TipoBajaActivoFieldSpecified;
        }
        set
        {
            this.pardet_TipoBajaActivoFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=30)]
    public int Pardet_Ubicacion
    {
        get
        {
            return this.pardet_UbicacionField;
        }
        set
        {
            this.pardet_UbicacionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool Pardet_UbicacionSpecified
    {
        get
        {
            return this.pardet_UbicacionFieldSpecified;
        }
        set
        {
            this.pardet_UbicacionFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=31)]
    public bool esNuevo
    {
        get
        {
            return this.esNuevoField;
        }
        set
        {
            this.esNuevoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool esNuevoSpecified
    {
        get
        {
            return this.esNuevoFieldSpecified;
        }
        set
        {
            this.esNuevoFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("NetCFSvcUtil", "3.5.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/ActivosFijosServices")]
public partial class Caracteristica
{
    
    private string actCar_DescripcionField;
    
    private string caracteristicaTextField;
    
    private int parame_CaracteristicaField;
    
    private bool parame_CaracteristicaFieldSpecified;
    
    private int pardet_CaracteristicaField;
    
    private bool pardet_CaracteristicaFieldSpecified;
    
    private bool esNuevoField;
    
    private bool esNuevoFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
    public string ActCar_Descripcion
    {
        get
        {
            return this.actCar_DescripcionField;
        }
        set
        {
            this.actCar_DescripcionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
    public string CaracteristicaText
    {
        get
        {
            return this.caracteristicaTextField;
        }
        set
        {
            this.caracteristicaTextField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public int Parame_Caracteristica
    {
        get
        {
            return this.parame_CaracteristicaField;
        }
        set
        {
            this.parame_CaracteristicaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool Parame_CaracteristicaSpecified
    {
        get
        {
            return this.parame_CaracteristicaFieldSpecified;
        }
        set
        {
            this.parame_CaracteristicaFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public int Pardet_Caracteristica
    {
        get
        {
            return this.pardet_CaracteristicaField;
        }
        set
        {
            this.pardet_CaracteristicaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool Pardet_CaracteristicaSpecified
    {
        get
        {
            return this.pardet_CaracteristicaFieldSpecified;
        }
        set
        {
            this.pardet_CaracteristicaFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public bool esNuevo
    {
        get
        {
            return this.esNuevoField;
        }
        set
        {
            this.esNuevoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool esNuevoSpecified
    {
        get
        {
            return this.esNuevoFieldSpecified;
        }
        set
        {
            this.esNuevoFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("NetCFSvcUtil", "3.5.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/ActivosFijosServices")]
public partial class Parametro
{
    
    private string descripcionField;
    
    private int parame_CodigoField;
    
    private bool parame_CodigoFieldSpecified;
    
    private int pardet_SecuenciaField;
    
    private bool pardet_SecuenciaFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
    public string Descripcion
    {
        get
        {
            return this.descripcionField;
        }
        set
        {
            this.descripcionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public int Parame_Codigo
    {
        get
        {
            return this.parame_CodigoField;
        }
        set
        {
            this.parame_CodigoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool Parame_CodigoSpecified
    {
        get
        {
            return this.parame_CodigoFieldSpecified;
        }
        set
        {
            this.parame_CodigoFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public int Pardet_Secuencia
    {
        get
        {
            return this.pardet_SecuenciaField;
        }
        set
        {
            this.pardet_SecuenciaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool Pardet_SecuenciaSpecified
    {
        get
        {
            return this.pardet_SecuenciaFieldSpecified;
        }
        set
        {
            this.pardet_SecuenciaFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("NetCFSvcUtil", "3.5.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/ActivosFijosServices")]
public partial class Proveedor
{
    
    private string nombreCompletoField;
    
    private int provee_CodigoField;
    
    private bool provee_CodigoFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
    public string NombreCompleto
    {
        get
        {
            return this.nombreCompletoField;
        }
        set
        {
            this.nombreCompletoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public int Provee_Codigo
    {
        get
        {
            return this.provee_CodigoField;
        }
        set
        {
            this.provee_CodigoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool Provee_CodigoSpecified
    {
        get
        {
            return this.provee_CodigoFieldSpecified;
        }
        set
        {
            this.provee_CodigoFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("NetCFSvcUtil", "3.5.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/ActivosFijosServices")]
public partial class Factura
{
    
    private int factura_CodigoField;
    
    private bool factura_CodigoFieldSpecified;
    
    private string proveedorField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public int Factura_Codigo
    {
        get
        {
            return this.factura_CodigoField;
        }
        set
        {
            this.factura_CodigoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool Factura_CodigoSpecified
    {
        get
        {
            return this.factura_CodigoFieldSpecified;
        }
        set
        {
            this.factura_CodigoFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
    public string Proveedor
    {
        get
        {
            return this.proveedorField;
        }
        set
        {
            this.proveedorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("NetCFSvcUtil", "3.5.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/ActivosFijosServices")]
public partial class Empleado
{
    
    private int emplea_CustodioField;
    
    private bool emplea_CustodioFieldSpecified;
    
    private string nombreCompletoField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public int Emplea_Custodio
    {
        get
        {
            return this.emplea_CustodioField;
        }
        set
        {
            this.emplea_CustodioField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool Emplea_CustodioSpecified
    {
        get
        {
            return this.emplea_CustodioFieldSpecified;
        }
        set
        {
            this.emplea_CustodioFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
    public string NombreCompleto
    {
        get
        {
            return this.nombreCompletoField;
        }
        set
        {
            this.nombreCompletoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("NetCFSvcUtil", "3.5.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/ActivosFijosServices")]
public partial class Inventario
{
    
    private string descripcionField;
    
    private System.DateTime invent_FechaField;
    
    private bool invent_FechaFieldSpecified;
    
    private int parame_EstadoInventarioField;
    
    private bool parame_EstadoInventarioFieldSpecified;
    
    private int parame_PeriodoInventarioField;
    
    private bool parame_PeriodoInventarioFieldSpecified;
    
    private int parame_UbicacionField;
    
    private bool parame_UbicacionFieldSpecified;
    
    private int pardet_EstadoInventarioField;
    
    private bool pardet_EstadoInventarioFieldSpecified;
    
    private int pardet_PeriodoInventarioField;
    
    private bool pardet_PeriodoInventarioFieldSpecified;
    
    private int pardet_UbicacionField;
    
    private bool pardet_UbicacionFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
    public string Descripcion
    {
        get
        {
            return this.descripcionField;
        }
        set
        {
            this.descripcionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public System.DateTime Invent_Fecha
    {
        get
        {
            return this.invent_FechaField;
        }
        set
        {
            this.invent_FechaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool Invent_FechaSpecified
    {
        get
        {
            return this.invent_FechaFieldSpecified;
        }
        set
        {
            this.invent_FechaFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public int Parame_EstadoInventario
    {
        get
        {
            return this.parame_EstadoInventarioField;
        }
        set
        {
            this.parame_EstadoInventarioField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool Parame_EstadoInventarioSpecified
    {
        get
        {
            return this.parame_EstadoInventarioFieldSpecified;
        }
        set
        {
            this.parame_EstadoInventarioFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public int Parame_PeriodoInventario
    {
        get
        {
            return this.parame_PeriodoInventarioField;
        }
        set
        {
            this.parame_PeriodoInventarioField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool Parame_PeriodoInventarioSpecified
    {
        get
        {
            return this.parame_PeriodoInventarioFieldSpecified;
        }
        set
        {
            this.parame_PeriodoInventarioFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public int Parame_Ubicacion
    {
        get
        {
            return this.parame_UbicacionField;
        }
        set
        {
            this.parame_UbicacionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool Parame_UbicacionSpecified
    {
        get
        {
            return this.parame_UbicacionFieldSpecified;
        }
        set
        {
            this.parame_UbicacionFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=5)]
    public int Pardet_EstadoInventario
    {
        get
        {
            return this.pardet_EstadoInventarioField;
        }
        set
        {
            this.pardet_EstadoInventarioField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool Pardet_EstadoInventarioSpecified
    {
        get
        {
            return this.pardet_EstadoInventarioFieldSpecified;
        }
        set
        {
            this.pardet_EstadoInventarioFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=6)]
    public int Pardet_PeriodoInventario
    {
        get
        {
            return this.pardet_PeriodoInventarioField;
        }
        set
        {
            this.pardet_PeriodoInventarioField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool Pardet_PeriodoInventarioSpecified
    {
        get
        {
            return this.pardet_PeriodoInventarioFieldSpecified;
        }
        set
        {
            this.pardet_PeriodoInventarioFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=7)]
    public int Pardet_Ubicacion
    {
        get
        {
            return this.pardet_UbicacionField;
        }
        set
        {
            this.pardet_UbicacionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool Pardet_UbicacionSpecified
    {
        get
        {
            return this.pardet_UbicacionFieldSpecified;
        }
        set
        {
            this.pardet_UbicacionFieldSpecified = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="CargarActivo", Namespace="http://tempuri.org/")]
public partial class CargarActivoRequest
{
    
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Namespace="http://tempuri.org/", Order=0)]
    public string Activo_Codigo;
    
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Namespace="http://tempuri.org/", Order=1)]
    public string Serie;
    
    public CargarActivoRequest()
    {
    }
    
    public CargarActivoRequest(string Activo_Codigo, string Serie)
    {
        this.Activo_Codigo = Activo_Codigo;
        this.Serie = Serie;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="CargarActivoResponse", Namespace="http://tempuri.org/")]
public partial class CargarActivoResponse
{
    
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Namespace="http://tempuri.org/", Order=0)]
    public Activo CargarActivoResult;
    
    public CargarActivoResponse()
    {
    }
    
    public CargarActivoResponse(Activo CargarActivoResult)
    {
        this.CargarActivoResult = CargarActivoResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="ActivoInventariado", Namespace="http://tempuri.org/")]
public partial class ActivoInventariadoRequest
{
    
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://tempuri.org/", Order=0)]
    public int Activo_Codigo;
    
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://tempuri.org/", Order=1)]
    public int Parame_PeriodoInventario;
    
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://tempuri.org/", Order=2)]
    public int Pardet_PeriodoInventario;
    
    public ActivoInventariadoRequest()
    {
    }
    
    public ActivoInventariadoRequest(int Activo_Codigo, int Parame_PeriodoInventario, int Pardet_PeriodoInventario)
    {
        this.Activo_Codigo = Activo_Codigo;
        this.Parame_PeriodoInventario = Parame_PeriodoInventario;
        this.Pardet_PeriodoInventario = Pardet_PeriodoInventario;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="ActivoInventariadoResponse", Namespace="http://tempuri.org/")]
public partial class ActivoInventariadoResponse
{
    
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://tempuri.org/", Order=0)]
    public bool ActivoInventariadoResult;
    
    public ActivoInventariadoResponse()
    {
    }
    
    public ActivoInventariadoResponse(bool ActivoInventariadoResult)
    {
        this.ActivoInventariadoResult = ActivoInventariadoResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="GuardarInventarioDet", Namespace="http://tempuri.org/")]
public partial class GuardarInventarioDetRequest
{
    
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Namespace="http://tempuri.org/", Order=0)]
    public string mUsuario;
    
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Namespace="http://tempuri.org/", Order=1)]
    public Inventario mInventario;
    
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Namespace="http://tempuri.org/", Order=2)]
    public Activo mActivo;
    
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://tempuri.org/", Order=3)]
    public int mCustodio;
    
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://tempuri.org/", Order=4)]
    public int mParame_Ubicacion;
    
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://tempuri.org/", Order=5)]
    public int mPardet_Ubicacion;
    
    public GuardarInventarioDetRequest()
    {
    }
    
    public GuardarInventarioDetRequest(string mUsuario, Inventario mInventario, Activo mActivo, int mCustodio, int mParame_Ubicacion, int mPardet_Ubicacion)
    {
        this.mUsuario = mUsuario;
        this.mInventario = mInventario;
        this.mActivo = mActivo;
        this.mCustodio = mCustodio;
        this.mParame_Ubicacion = mParame_Ubicacion;
        this.mPardet_Ubicacion = mPardet_Ubicacion;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="GuardarInventarioDetResponse", Namespace="http://tempuri.org/")]
public partial class GuardarInventarioDetResponse
{
    
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Namespace="http://tempuri.org/", Order=0)]
    public string GuardarInventarioDetResult;
    
    public GuardarInventarioDetResponse()
    {
    }
    
    public GuardarInventarioDetResponse(string GuardarInventarioDetResult)
    {
        this.GuardarInventarioDetResult = GuardarInventarioDetResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="IniciarSesion", Namespace="http://tempuri.org/")]
public partial class IniciarSesionRequest
{
    
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Namespace="http://tempuri.org/", Order=0)]
    public string mUsuario;
    
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Namespace="http://tempuri.org/", Order=1)]
    public string mContrasena;
    
    public IniciarSesionRequest()
    {
    }
    
    public IniciarSesionRequest(string mUsuario, string mContrasena)
    {
        this.mUsuario = mUsuario;
        this.mContrasena = mContrasena;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="IniciarSesionResponse", Namespace="http://tempuri.org/")]
public partial class IniciarSesionResponse
{
    
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://tempuri.org/", Order=0)]
    public bool IniciarSesionResult;
    
    public IniciarSesionResponse()
    {
    }
    
    public IniciarSesionResponse(bool IniciarSesionResult)
    {
        this.IniciarSesionResult = IniciarSesionResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="InventariosActivos", Namespace="http://tempuri.org/")]
public partial class InventariosActivosRequest
{
    
    public InventariosActivosRequest()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="InventariosActivosResponse", Namespace="http://tempuri.org/")]
public partial class InventariosActivosResponse
{
    
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Namespace="http://tempuri.org/", Order=0)]
    [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/ActivosFijosServices")]
    public Inventario[] InventariosActivosResult;
    
    public InventariosActivosResponse()
    {
    }
    
    public InventariosActivosResponse(Inventario[] InventariosActivosResult)
    {
        this.InventariosActivosResult = InventariosActivosResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="ListaCaracteristicas", Namespace="http://tempuri.org/")]
public partial class ListaCaracteristicasRequest
{
    
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://tempuri.org/", Order=0)]
    public int parame_tipo;
    
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://tempuri.org/", Order=1)]
    public int pardet_tipo;
    
    public ListaCaracteristicasRequest()
    {
    }
    
    public ListaCaracteristicasRequest(int parame_tipo, int pardet_tipo)
    {
        this.parame_tipo = parame_tipo;
        this.pardet_tipo = pardet_tipo;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="ListaCaracteristicasResponse", Namespace="http://tempuri.org/")]
public partial class ListaCaracteristicasResponse
{
    
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Namespace="http://tempuri.org/", Order=0)]
    [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/ActivosFijosServices")]
    public Caracteristica[] ListaCaracteristicasResult;
    
    public ListaCaracteristicasResponse()
    {
    }
    
    public ListaCaracteristicasResponse(Caracteristica[] ListaCaracteristicasResult)
    {
        this.ListaCaracteristicasResult = ListaCaracteristicasResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="ListaEmpleados", Namespace="http://tempuri.org/")]
public partial class ListaEmpleadosRequest
{
    
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Namespace="http://tempuri.org/", Order=0)]
    public string parcial;
    
    public ListaEmpleadosRequest()
    {
    }
    
    public ListaEmpleadosRequest(string parcial)
    {
        this.parcial = parcial;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="ListaEmpleadosResponse", Namespace="http://tempuri.org/")]
public partial class ListaEmpleadosResponse
{
    
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Namespace="http://tempuri.org/", Order=0)]
    [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/ActivosFijosServices")]
    public Empleado[] ListaEmpleadosResult;
    
    public ListaEmpleadosResponse()
    {
    }
    
    public ListaEmpleadosResponse(Empleado[] ListaEmpleadosResult)
    {
        this.ListaEmpleadosResult = ListaEmpleadosResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="ListaFacturas", Namespace="http://tempuri.org/")]
public partial class ListaFacturasRequest
{
    
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://tempuri.org/", Order=0)]
    public int _proveedor;
    
    public ListaFacturasRequest()
    {
    }
    
    public ListaFacturasRequest(int _proveedor)
    {
        this._proveedor = _proveedor;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="ListaFacturasResponse", Namespace="http://tempuri.org/")]
public partial class ListaFacturasResponse
{
    
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Namespace="http://tempuri.org/", Order=0)]
    [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/ActivosFijosServices")]
    public Factura[] ListaFacturasResult;
    
    public ListaFacturasResponse()
    {
    }
    
    public ListaFacturasResponse(Factura[] ListaFacturasResult)
    {
        this.ListaFacturasResult = ListaFacturasResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="ListaProveedores", Namespace="http://tempuri.org/")]
public partial class ListaProveedoresRequest
{
    
    public ListaProveedoresRequest()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="ListaProveedoresResponse", Namespace="http://tempuri.org/")]
public partial class ListaProveedoresResponse
{
    
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Namespace="http://tempuri.org/", Order=0)]
    [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/ActivosFijosServices")]
    public Proveedor[] ListaProveedoresResult;
    
    public ListaProveedoresResponse()
    {
    }
    
    public ListaProveedoresResponse(Proveedor[] ListaProveedoresResult)
    {
        this.ListaProveedoresResult = ListaProveedoresResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="ParametroList", Namespace="http://tempuri.org/")]
public partial class ParametroListRequest
{
    
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://tempuri.org/", Order=0)]
    public int parame_codigo;
    
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://tempuri.org/", Order=1)]
    public int parame_padre;
    
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://tempuri.org/", Order=2)]
    public int pardet_padre;
    
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Namespace="http://tempuri.org/", Order=3)]
    public string filtro;
    
    public ParametroListRequest()
    {
    }
    
    public ParametroListRequest(int parame_codigo, int parame_padre, int pardet_padre, string filtro)
    {
        this.parame_codigo = parame_codigo;
        this.parame_padre = parame_padre;
        this.pardet_padre = pardet_padre;
        this.filtro = filtro;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="ParametroListResponse", Namespace="http://tempuri.org/")]
public partial class ParametroListResponse
{
    
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Namespace="http://tempuri.org/", Order=0)]
    [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/ActivosFijosServices")]
    public Parametro[] ParametroListResult;
    
    public ParametroListResponse()
    {
    }
    
    public ParametroListResponse(Parametro[] ParametroListResult)
    {
        this.ParametroListResult = ParametroListResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="ParametroTreeList", Namespace="http://tempuri.org/")]
public partial class ParametroTreeListRequest
{
    
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://tempuri.org/", Order=0)]
    public int parame_inicio;
    
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://tempuri.org/", Order=1)]
    public int pardet_inicio;
    
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://tempuri.org/", Order=2)]
    public int parame_fin;
    
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://tempuri.org/", Order=3)]
    public bool solo_visibles;
    
    public ParametroTreeListRequest()
    {
    }
    
    public ParametroTreeListRequest(int parame_inicio, int pardet_inicio, int parame_fin, bool solo_visibles)
    {
        this.parame_inicio = parame_inicio;
        this.pardet_inicio = pardet_inicio;
        this.parame_fin = parame_fin;
        this.solo_visibles = solo_visibles;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="ParametroTreeListResponse", Namespace="http://tempuri.org/")]
public partial class ParametroTreeListResponse
{
    
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Namespace="http://tempuri.org/", Order=0)]
    [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/ActivosFijosServices")]
    public Parametro[] ParametroTreeListResult;
    
    public ParametroTreeListResponse()
    {
    }
    
    public ParametroTreeListResponse(Parametro[] ParametroTreeListResult)
    {
        this.ParametroTreeListResult = ParametroTreeListResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class ActivosFijosServiceClient : Microsoft.Tools.ServiceModel.CFClientBase<IActivosFijosService>, IActivosFijosService
{
    
    public static System.ServiceModel.EndpointAddress EndpointAddress = new System.ServiceModel.EndpointAddress("http://localhost/WSActivosFijos/ActivosFijos.svc");
    
    public ActivosFijosServiceClient() : 
            this(CreateDefaultBinding(), EndpointAddress)
    {
    }
    
    public ActivosFijosServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
        addProtectionRequirements(binding);
    }
    
    private CargarActivoResponse CargarActivo(CargarActivoRequest request)
    {
        CFInvokeInfo info = new CFInvokeInfo();
        info.Action = "http://tempuri.org/IActivosFijosService/CargarActivo";
        info.RequestIsWrapped = true;
        info.ReplyAction = "http://tempuri.org/IActivosFijosService/CargarActivoResponse";
        info.ResponseIsWrapped = true;
        CargarActivoResponse retVal = base.Invoke<CargarActivoRequest, CargarActivoResponse>(info, request);
        return retVal;
    }
    
    public Activo CargarActivo(string Activo_Codigo, string Serie)
    {
        CargarActivoRequest request = new CargarActivoRequest(Activo_Codigo, Serie);
        CargarActivoResponse response = this.CargarActivo(request);
        return response.CargarActivoResult;
    }
    
    private ActivoInventariadoResponse ActivoInventariado(ActivoInventariadoRequest request)
    {
        CFInvokeInfo info = new CFInvokeInfo();
        info.Action = "http://tempuri.org/IActivosFijosService/ActivoInventariado";
        info.RequestIsWrapped = true;
        info.ReplyAction = "http://tempuri.org/IActivosFijosService/ActivoInventariadoResponse";
        info.ResponseIsWrapped = true;
        ActivoInventariadoResponse retVal = base.Invoke<ActivoInventariadoRequest, ActivoInventariadoResponse>(info, request);
        return retVal;
    }
    
    public bool ActivoInventariado(int Activo_Codigo, int Parame_PeriodoInventario, int Pardet_PeriodoInventario)
    {
        ActivoInventariadoRequest request = new ActivoInventariadoRequest(Activo_Codigo, Parame_PeriodoInventario, Pardet_PeriodoInventario);
        ActivoInventariadoResponse response = this.ActivoInventariado(request);
        return response.ActivoInventariadoResult;
    }
    
    private GuardarInventarioDetResponse GuardarInventarioDet(GuardarInventarioDetRequest request)
    {
        CFInvokeInfo info = new CFInvokeInfo();
        info.Action = "http://tempuri.org/IActivosFijosService/GuardarInventarioDet";
        info.RequestIsWrapped = true;
        info.ReplyAction = "http://tempuri.org/IActivosFijosService/GuardarInventarioDetResponse";
        info.ResponseIsWrapped = true;
        GuardarInventarioDetResponse retVal = base.Invoke<GuardarInventarioDetRequest, GuardarInventarioDetResponse>(info, request);
        return retVal;
    }
    
    public string GuardarInventarioDet(string mUsuario, Inventario mInventario, Activo mActivo, int mCustodio, int mParame_Ubicacion, int mPardet_Ubicacion)
    {
        GuardarInventarioDetRequest request = new GuardarInventarioDetRequest(mUsuario, mInventario, mActivo, mCustodio, mParame_Ubicacion, mPardet_Ubicacion);
        GuardarInventarioDetResponse response = this.GuardarInventarioDet(request);
        return response.GuardarInventarioDetResult;
    }
    
    private IniciarSesionResponse IniciarSesion(IniciarSesionRequest request)
    {
        CFInvokeInfo info = new CFInvokeInfo();
        info.Action = "http://tempuri.org/IActivosFijosService/IniciarSesion";
        info.RequestIsWrapped = true;
        info.ReplyAction = "http://tempuri.org/IActivosFijosService/IniciarSesionResponse";
        info.ResponseIsWrapped = true;
        IniciarSesionResponse retVal = base.Invoke<IniciarSesionRequest, IniciarSesionResponse>(info, request);
        return retVal;
    }
    
    public bool IniciarSesion(string mUsuario, string mContrasena)
    {
        IniciarSesionRequest request = new IniciarSesionRequest(mUsuario, mContrasena);
        IniciarSesionResponse response = this.IniciarSesion(request);
        return response.IniciarSesionResult;
    }
    
    private InventariosActivosResponse InventariosActivos(InventariosActivosRequest request)
    {
        CFInvokeInfo info = new CFInvokeInfo();
        info.Action = "http://tempuri.org/IActivosFijosService/InventariosActivos";
        info.RequestIsWrapped = true;
        info.ReplyAction = "http://tempuri.org/IActivosFijosService/InventariosActivosResponse";
        info.ResponseIsWrapped = true;
        InventariosActivosResponse retVal = base.Invoke<InventariosActivosRequest, InventariosActivosResponse>(info, request);
        return retVal;
    }
    
    public Inventario[] InventariosActivos()
    {
        InventariosActivosRequest request = new InventariosActivosRequest();
        InventariosActivosResponse response = this.InventariosActivos(request);
        return response.InventariosActivosResult;
    }
    
    private ListaCaracteristicasResponse ListaCaracteristicas(ListaCaracteristicasRequest request)
    {
        CFInvokeInfo info = new CFInvokeInfo();
        info.Action = "http://tempuri.org/IActivosFijosService/ListaCaracteristicas";
        info.RequestIsWrapped = true;
        info.ReplyAction = "http://tempuri.org/IActivosFijosService/ListaCaracteristicasResponse";
        info.ResponseIsWrapped = true;
        ListaCaracteristicasResponse retVal = base.Invoke<ListaCaracteristicasRequest, ListaCaracteristicasResponse>(info, request);
        return retVal;
    }
    
    public Caracteristica[] ListaCaracteristicas(int parame_tipo, int pardet_tipo)
    {
        ListaCaracteristicasRequest request = new ListaCaracteristicasRequest(parame_tipo, pardet_tipo);
        ListaCaracteristicasResponse response = this.ListaCaracteristicas(request);
        return response.ListaCaracteristicasResult;
    }
    
    private ListaEmpleadosResponse ListaEmpleados(ListaEmpleadosRequest request)
    {
        CFInvokeInfo info = new CFInvokeInfo();
        info.Action = "http://tempuri.org/IActivosFijosService/ListaEmpleados";
        info.RequestIsWrapped = true;
        info.ReplyAction = "http://tempuri.org/IActivosFijosService/ListaEmpleadosResponse";
        info.ResponseIsWrapped = true;
        ListaEmpleadosResponse retVal = base.Invoke<ListaEmpleadosRequest, ListaEmpleadosResponse>(info, request);
        return retVal;
    }
    
    public Empleado[] ListaEmpleados(string parcial)
    {
        ListaEmpleadosRequest request = new ListaEmpleadosRequest(parcial);
        ListaEmpleadosResponse response = this.ListaEmpleados(request);
        return response.ListaEmpleadosResult;
    }
    
    private ListaFacturasResponse ListaFacturas(ListaFacturasRequest request)
    {
        CFInvokeInfo info = new CFInvokeInfo();
        info.Action = "http://tempuri.org/IActivosFijosService/ListaFacturas";
        info.RequestIsWrapped = true;
        info.ReplyAction = "http://tempuri.org/IActivosFijosService/ListaFacturasResponse";
        info.ResponseIsWrapped = true;
        ListaFacturasResponse retVal = base.Invoke<ListaFacturasRequest, ListaFacturasResponse>(info, request);
        return retVal;
    }
    
    public Factura[] ListaFacturas(int _proveedor)
    {
        ListaFacturasRequest request = new ListaFacturasRequest(_proveedor);
        ListaFacturasResponse response = this.ListaFacturas(request);
        return response.ListaFacturasResult;
    }
    
    private ListaProveedoresResponse ListaProveedores(ListaProveedoresRequest request)
    {
        CFInvokeInfo info = new CFInvokeInfo();
        info.Action = "http://tempuri.org/IActivosFijosService/ListaProveedores";
        info.RequestIsWrapped = true;
        info.ReplyAction = "http://tempuri.org/IActivosFijosService/ListaProveedoresResponse";
        info.ResponseIsWrapped = true;
        ListaProveedoresResponse retVal = base.Invoke<ListaProveedoresRequest, ListaProveedoresResponse>(info, request);
        return retVal;
    }
    
    public Proveedor[] ListaProveedores()
    {
        ListaProveedoresRequest request = new ListaProveedoresRequest();
        ListaProveedoresResponse response = this.ListaProveedores(request);
        return response.ListaProveedoresResult;
    }
    
    private ParametroListResponse ParametroList(ParametroListRequest request)
    {
        CFInvokeInfo info = new CFInvokeInfo();
        info.Action = "http://tempuri.org/IActivosFijosService/ParametroList";
        info.RequestIsWrapped = true;
        info.ReplyAction = "http://tempuri.org/IActivosFijosService/ParametroListResponse";
        info.ResponseIsWrapped = true;
        ParametroListResponse retVal = base.Invoke<ParametroListRequest, ParametroListResponse>(info, request);
        return retVal;
    }
    
    public Parametro[] ParametroList(int parame_codigo, int parame_padre, int pardet_padre, string filtro)
    {
        ParametroListRequest request = new ParametroListRequest(parame_codigo, parame_padre, pardet_padre, filtro);
        ParametroListResponse response = this.ParametroList(request);
        return response.ParametroListResult;
    }
    
    private ParametroTreeListResponse ParametroTreeList(ParametroTreeListRequest request)
    {
        CFInvokeInfo info = new CFInvokeInfo();
        info.Action = "http://tempuri.org/IActivosFijosService/ParametroTreeList";
        info.RequestIsWrapped = true;
        info.ReplyAction = "http://tempuri.org/IActivosFijosService/ParametroTreeListResponse";
        info.ResponseIsWrapped = true;
        ParametroTreeListResponse retVal = base.Invoke<ParametroTreeListRequest, ParametroTreeListResponse>(info, request);
        return retVal;
    }
    
    public Parametro[] ParametroTreeList(int parame_inicio, int pardet_inicio, int parame_fin, bool solo_visibles)
    {
        ParametroTreeListRequest request = new ParametroTreeListRequest(parame_inicio, pardet_inicio, parame_fin, solo_visibles);
        ParametroTreeListResponse response = this.ParametroTreeList(request);
        return response.ParametroTreeListResult;
    }
    
    public static System.ServiceModel.Channels.Binding CreateDefaultBinding()
    {
        System.ServiceModel.Channels.CustomBinding binding = new System.ServiceModel.Channels.CustomBinding();
        binding.Elements.Add(new System.ServiceModel.Channels.TextMessageEncodingBindingElement(System.ServiceModel.Channels.MessageVersion.Soap11, System.Text.Encoding.UTF8));
        binding.Elements.Add(new System.ServiceModel.Channels.HttpTransportBindingElement());
        return binding;
    }
    
    private void addProtectionRequirements(System.ServiceModel.Channels.Binding binding)
    {
        if ((IsSecureMessageBinding(binding) == false))
        {
            return;
        }
        System.ServiceModel.Security.ChannelProtectionRequirements cpr = new System.ServiceModel.Security.ChannelProtectionRequirements();
        ApplyProtection("http://tempuri.org/IActivosFijosService/CargarActivo", cpr.IncomingSignatureParts, true);
        ApplyProtection("http://tempuri.org/IActivosFijosService/CargarActivo", cpr.IncomingEncryptionParts, true);
        ApplyProtection("http://tempuri.org/IActivosFijosService/ActivoInventariado", cpr.IncomingSignatureParts, true);
        ApplyProtection("http://tempuri.org/IActivosFijosService/ActivoInventariado", cpr.IncomingEncryptionParts, true);
        ApplyProtection("http://tempuri.org/IActivosFijosService/GuardarInventarioDet", cpr.IncomingSignatureParts, true);
        ApplyProtection("http://tempuri.org/IActivosFijosService/GuardarInventarioDet", cpr.IncomingEncryptionParts, true);
        ApplyProtection("http://tempuri.org/IActivosFijosService/IniciarSesion", cpr.IncomingSignatureParts, true);
        ApplyProtection("http://tempuri.org/IActivosFijosService/IniciarSesion", cpr.IncomingEncryptionParts, true);
        ApplyProtection("http://tempuri.org/IActivosFijosService/InventariosActivos", cpr.IncomingSignatureParts, true);
        ApplyProtection("http://tempuri.org/IActivosFijosService/InventariosActivos", cpr.IncomingEncryptionParts, true);
        ApplyProtection("http://tempuri.org/IActivosFijosService/ListaCaracteristicas", cpr.IncomingSignatureParts, true);
        ApplyProtection("http://tempuri.org/IActivosFijosService/ListaCaracteristicas", cpr.IncomingEncryptionParts, true);
        ApplyProtection("http://tempuri.org/IActivosFijosService/ListaEmpleados", cpr.IncomingSignatureParts, true);
        ApplyProtection("http://tempuri.org/IActivosFijosService/ListaEmpleados", cpr.IncomingEncryptionParts, true);
        ApplyProtection("http://tempuri.org/IActivosFijosService/ListaFacturas", cpr.IncomingSignatureParts, true);
        ApplyProtection("http://tempuri.org/IActivosFijosService/ListaFacturas", cpr.IncomingEncryptionParts, true);
        ApplyProtection("http://tempuri.org/IActivosFijosService/ListaProveedores", cpr.IncomingSignatureParts, true);
        ApplyProtection("http://tempuri.org/IActivosFijosService/ListaProveedores", cpr.IncomingEncryptionParts, true);
        ApplyProtection("http://tempuri.org/IActivosFijosService/ParametroList", cpr.IncomingSignatureParts, true);
        ApplyProtection("http://tempuri.org/IActivosFijosService/ParametroList", cpr.IncomingEncryptionParts, true);
        ApplyProtection("http://tempuri.org/IActivosFijosService/ParametroTreeList", cpr.IncomingSignatureParts, true);
        ApplyProtection("http://tempuri.org/IActivosFijosService/ParametroTreeList", cpr.IncomingEncryptionParts, true);
        if ((binding.MessageVersion.Addressing == System.ServiceModel.Channels.AddressingVersion.None))
        {
            ApplyProtection("*", cpr.OutgoingSignatureParts, true);
            ApplyProtection("*", cpr.OutgoingEncryptionParts, true);
        }
        else
        {
            ApplyProtection("http://tempuri.org/IActivosFijosService/CargarActivoResponse", cpr.OutgoingSignatureParts, true);
            ApplyProtection("http://tempuri.org/IActivosFijosService/CargarActivoResponse", cpr.OutgoingEncryptionParts, true);
            ApplyProtection("http://tempuri.org/IActivosFijosService/ActivoInventariadoResponse", cpr.OutgoingSignatureParts, true);
            ApplyProtection("http://tempuri.org/IActivosFijosService/ActivoInventariadoResponse", cpr.OutgoingEncryptionParts, true);
            ApplyProtection("http://tempuri.org/IActivosFijosService/GuardarInventarioDetResponse", cpr.OutgoingSignatureParts, true);
            ApplyProtection("http://tempuri.org/IActivosFijosService/GuardarInventarioDetResponse", cpr.OutgoingEncryptionParts, true);
            ApplyProtection("http://tempuri.org/IActivosFijosService/IniciarSesionResponse", cpr.OutgoingSignatureParts, true);
            ApplyProtection("http://tempuri.org/IActivosFijosService/IniciarSesionResponse", cpr.OutgoingEncryptionParts, true);
            ApplyProtection("http://tempuri.org/IActivosFijosService/InventariosActivosResponse", cpr.OutgoingSignatureParts, true);
            ApplyProtection("http://tempuri.org/IActivosFijosService/InventariosActivosResponse", cpr.OutgoingEncryptionParts, true);
            ApplyProtection("http://tempuri.org/IActivosFijosService/ListaCaracteristicasResponse", cpr.OutgoingSignatureParts, true);
            ApplyProtection("http://tempuri.org/IActivosFijosService/ListaCaracteristicasResponse", cpr.OutgoingEncryptionParts, true);
            ApplyProtection("http://tempuri.org/IActivosFijosService/ListaEmpleadosResponse", cpr.OutgoingSignatureParts, true);
            ApplyProtection("http://tempuri.org/IActivosFijosService/ListaEmpleadosResponse", cpr.OutgoingEncryptionParts, true);
            ApplyProtection("http://tempuri.org/IActivosFijosService/ListaFacturasResponse", cpr.OutgoingSignatureParts, true);
            ApplyProtection("http://tempuri.org/IActivosFijosService/ListaFacturasResponse", cpr.OutgoingEncryptionParts, true);
            ApplyProtection("http://tempuri.org/IActivosFijosService/ListaProveedoresResponse", cpr.OutgoingSignatureParts, true);
            ApplyProtection("http://tempuri.org/IActivosFijosService/ListaProveedoresResponse", cpr.OutgoingEncryptionParts, true);
            ApplyProtection("http://tempuri.org/IActivosFijosService/ParametroListResponse", cpr.OutgoingSignatureParts, true);
            ApplyProtection("http://tempuri.org/IActivosFijosService/ParametroListResponse", cpr.OutgoingEncryptionParts, true);
            ApplyProtection("http://tempuri.org/IActivosFijosService/ParametroTreeListResponse", cpr.OutgoingSignatureParts, true);
            ApplyProtection("http://tempuri.org/IActivosFijosService/ParametroTreeListResponse", cpr.OutgoingEncryptionParts, true);
        }
        this.Parameters.Add(cpr);
    }
}
