'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión del motor en tiempo de ejecución:2.0.50727.5446
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports Infoware.Reglas
Imports System
Imports System.Xml
Imports System.Xml.Serialization


#Region "ActivoUbicacion"
Partial Public Class ActivoUbicacion
    Inherits _Database
    
    Private mActivo_Codigo As Integer = 0
    
    Private mActUbi_Secuencia As Integer = 0
    
    Private mActUbi_Activo As Boolean = true
    
    Private mParame_Ubicacion As Integer = 0
    
    Private mPardet_Ubicacion As Integer = 0
    
  Private mActUbi_FechaDesde As Date = Now.Date
    
  Private mActUbi_FechaHasta As Date = Nothing

  Private mTransa_Codigo As Integer = 0

    Public Sub New()
        MyBase.New
    End Sub
    
    <XmlAttribute()>  _
    Public Overridable Property Activo_Codigo() As Integer
        Get
            Return Me.mActivo_Codigo
        End Get
        Set
            Me.mActivo_Codigo = value
            EsModificado = true
        End Set
    End Property
    
    <XmlAttribute()>  _
    Public Overridable Property ActUbi_Secuencia() As Integer
        Get
            Return Me.mActUbi_Secuencia
        End Get
        Set
            Me.mActUbi_Secuencia = value
            EsModificado = true
        End Set
    End Property
    
    <XmlAttribute()>  _
    Public Overridable Property ActUbi_Activo() As Boolean
        Get
            Return Me.mActUbi_Activo
        End Get
        Set
            Me.mActUbi_Activo = value
            EsModificado = true
        End Set
    End Property
    
    <XmlAttribute()>  _
    Public Overridable Property Parame_Ubicacion() As Integer
        Get
            Return Me.mParame_Ubicacion
        End Get
        Set
            Me.mParame_Ubicacion = value
            EsModificado = true
        End Set
    End Property
    
    <XmlAttribute()>  _
    Public Overridable Property Pardet_Ubicacion() As Integer
        Get
            Return Me.mPardet_Ubicacion
        End Get
        Set
            Me.mPardet_Ubicacion = value
            EsModificado = true
        End Set
    End Property
    
  <XmlAttribute()> _
  Public Overridable Property ActUbi_FechaDesde() As Date
    Get
      Return Me.mActUbi_FechaDesde
    End Get
    Set(value As Date)
      Me.mActUbi_FechaDesde = Value
      EsModificado = True
    End Set
  End Property
    
  <XmlAttribute()> _
  Public Overridable Property ActUbi_FechaHasta() As Date
    Get
      Return Me.mActUbi_FechaHasta
    End Get
    Set(value As Date)
      Me.mActUbi_FechaHasta = Value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Transa_Codigo() As Integer
    Get
      Return Me.mTransa_Codigo
    End Get
    Set(value As Integer)
      Me.mTransa_Codigo = value
      EsModificado = True
    End Set
  End Property
End Class
#End Region
