'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión del motor en tiempo de ejecución:2.0.50727.5446
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports Infoware.Reglas
Imports System
Imports System.Xml
Imports System.Xml.Serialization


#Region "ActivoCaracteristica"
Partial Public Class ActivoCaracteristica
  Inherits _Database

  Private mActivo_Codigo As Integer = 0

  Private mParame_Caracteristica As Integer = 0

  Private mPardet_Caracteristica As Integer = 0

  Private mActCar_Descripcion As String = String.Empty

  Public Sub New()
    MyBase.New()
  End Sub

  <XmlAttribute()> _
  Public Overridable Property Activo_Codigo() As Integer
    Get
      Return Me.mActivo_Codigo
    End Get
    Set(value As Integer)
      Me.mActivo_Codigo = Value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Parame_Caracteristica() As Integer
    Get
      Return Me.mParame_Caracteristica
    End Get
    Set(value As Integer)
      Me.mParame_Caracteristica = Value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Pardet_Caracteristica() As Integer
    Get
      Return Me.mPardet_Caracteristica
    End Get
    Set(value As Integer)
      Me.mPardet_Caracteristica = Value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property ActCar_Descripcion() As String
    Get
      Return Me.mActCar_Descripcion
    End Get
    Set(value As String)
      Me.mActCar_Descripcion = value
      EsModificado = True
    End Set
  End Property
End Class
#End Region
