'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión del motor en tiempo de ejecución:2.0.50727.5446
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports Infoware.Reglas
Imports System
Imports System.Xml
Imports System.Xml.Serialization


#Region "ActivoComponente"
Partial Public Class ActivoComponente
    Inherits _Database
    
    Private mActivo_Codigo As Integer = 0
    
    Private mActCom_Secuencia As Integer = 0
    
    Private mActCom_Activo As Boolean = true
    
    Private mActCom_Descripcion As String = ""
    
    Private mParame_Marca As Integer = 0
    
    Private mPardet_Marca As Integer = 0
    
  Private mActCom_Modelo As String = ""

  Private mActCom_Serie As String = ""

  Private mActCom_esErogacion As Boolean = False

  Private mActCom_ValorErogacion As Decimal = 0

  Private mActCom_FechaAdquisicion As Date = Now.Date

  Private mActCom_FechaIngreso As Date = Now.Date

  Private mEntida_Proveedor As Integer = 0

  Private mActCom_Factura As String = ""

  Private mActCom_FechaBaja As Date = Nothing

  Public Sub New()
    MyBase.New()
  End Sub

  <XmlAttribute()> _
  Public Overridable Property Activo_Codigo() As Integer
    Get
      Return Me.mActivo_Codigo
    End Get
    Set(value As Integer)
      Me.mActivo_Codigo = Value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property ActCom_Secuencia() As Integer
    Get
      Return Me.mActCom_Secuencia
    End Get
    Set(value As Integer)
      Me.mActCom_Secuencia = Value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property ActCom_Activo() As Boolean
    Get
      Return Me.mActCom_Activo
    End Get
    Set(value As Boolean)
      Me.mActCom_Activo = Value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property ActCom_Descripcion() As String
    Get
      Return Me.mActCom_Descripcion
    End Get
    Set(value As String)
      Me.mActCom_Descripcion = Value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Parame_Marca() As Integer
    Get
      Return Me.mParame_Marca
    End Get
    Set(value As Integer)
      Me.mParame_Marca = Value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Pardet_Marca() As Integer
    Get
      Return Me.mPardet_Marca
    End Get
    Set(value As Integer)
      Me.mPardet_Marca = Value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property ActCom_Modelo() As String
    Get
      Return Me.mActCom_Modelo
    End Get
    Set(value As String)
      Me.mActCom_Modelo = value
      EsModificado = True
    End Set
  End Property
    
  <XmlAttribute()> _
    Public Overridable Property ActCom_Serie() As String
    Get
      Return Me.mActCom_Serie
    End Get
    Set(value As String)
      Me.mActCom_Serie = Value
      EsModificado = True
    End Set
  End Property
    
    <XmlAttribute()>  _
    Public Overridable Property ActCom_esErogacion() As Boolean
        Get
            Return Me.mActCom_esErogacion
        End Get
        Set
            Me.mActCom_esErogacion = value
            EsModificado = true
        End Set
    End Property
    
    <XmlAttribute()>  _
    Public Overridable Property ActCom_ValorErogacion() As Decimal
        Get
            Return Me.mActCom_ValorErogacion
        End Get
        Set
            Me.mActCom_ValorErogacion = value
            EsModificado = true
        End Set
    End Property

  <XmlAttribute()> _
  Public Overridable Property ActCom_FechaAdquisicion() As Date
    Get
      Return Me.mActCom_FechaAdquisicion
    End Get
    Set(value As Date)
      Me.mActCom_FechaAdquisicion = Value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property ActCom_FechaIngreso() As Date
    Get
      Return Me.mActCom_FechaIngreso
    End Get
    Set(value As Date)
      Me.mActCom_FechaIngreso = value
      EsModificado = True
    End Set
  End Property

    <XmlAttribute()>  _
    Public Overridable Property Entida_Proveedor() As Integer
        Get
            Return Me.mEntida_Proveedor
        End Get
        Set
            Me.mEntida_Proveedor = value
            EsModificado = true
        End Set
    End Property
    
    <XmlAttribute()>  _
    Public Overridable Property ActCom_Factura() As String
        Get
            Return Me.mActCom_Factura
        End Get
        Set
            Me.mActCom_Factura = value
            EsModificado = true
        End Set
    End Property
    
  <XmlAttribute()> _
  Public Overridable Property ActCom_FechaBaja() As Date
    Get
      Return Me.mActCom_FechaBaja
    End Get
    Set(value As Date)
      Me.mActCom_FechaBaja = Value
      EsModificado = True
    End Set
  End Property
End Class
#End Region
