'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión del motor en tiempo de ejecución:2.0.50727.5446
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports Infoware.Reglas
Imports System
Imports System.Xml
Imports System.Xml.Serialization


#Region "ActivoCustodio"
Partial Public Class ActivoCustodio
  Inherits _Database

  Private mActivo_Codigo As Integer = 0

  Private mActCus_Secuencia As Integer = 0

  Private mActCus_Activo As Boolean = True

  Private mParame_AprobadoNuevoCustodio As Integer = 0

  Private mPardet_AprobadoNuevoCustodio As Integer = 0

  Private mActCus_FechaDesde As Date = Now.Date

  Private mActCus_FechaHasta As Date = Nothing

  Private mEmplea_Custodio As Integer = 0

  Private mActCus_Observacion As String = ""

  Private mTransa_Codigo As Integer = 0

  Public Sub New()
    MyBase.New()
  End Sub

  <XmlAttribute()> _
  Public Overridable Property Activo_Codigo() As Integer
    Get
      Return Me.mActivo_Codigo
    End Get
    Set(value As Integer)
      Me.mActivo_Codigo = Value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property ActCus_Secuencia() As Integer
    Get
      Return Me.mActCus_Secuencia
    End Get
    Set(value As Integer)
      Me.mActCus_Secuencia = Value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property ActCus_Activo() As Boolean
    Get
      Return Me.mActCus_Activo
    End Get
    Set(value As Boolean)
      Me.mActCus_Activo = Value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Parame_AprobadoNuevoCustodio() As Integer
    Get
      Return Me.mParame_AprobadoNuevoCustodio
    End Get
    Set(value As Integer)
      Me.mParame_AprobadoNuevoCustodio = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Pardet_AprobadoNuevoCustodio() As Integer
    Get
      Return Me.mPardet_AprobadoNuevoCustodio
    End Get
    Set(value As Integer)
      Me.mPardet_AprobadoNuevoCustodio = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property ActCus_FechaDesde() As Date
    Get
      Return Me.mActCus_FechaDesde
    End Get
    Set(value As Date)
      Me.mActCus_FechaDesde = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property ActCus_FechaHasta() As Date
    Get
      Return Me.mActCus_FechaHasta
    End Get
    Set(value As Date)
      Me.mActCus_FechaHasta = value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Emplea_Custodio() As Integer
    Get
      Return Me.mEmplea_Custodio
    End Get
    Set(value As Integer)
      Me.mEmplea_Custodio = Value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property ActCus_Observacion() As String
    Get
      Return Me.mActCus_Observacion
    End Get
    Set(value As String)
      Me.mActCus_Observacion = Value
      EsModificado = True
    End Set
  End Property

  <XmlAttribute()> _
  Public Overridable Property Transa_Codigo() As Integer
    Get
      Return Me.mTransa_Codigo
    End Get
    Set(value As Integer)
      Me.mTransa_Codigo = value
      EsModificado = True
    End Set
  End Property
End Class
#End Region
