'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión del motor en tiempo de ejecución:2.0.50727.5446
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports Infoware.Reglas
Imports System
Imports System.Xml
Imports System.Xml.Serialization


#Region "asientocontable"
Partial Public Class asientocontable
    Inherits _Database
    
    Private mfecha_proceso As String = ""
    
    Private mestado As Boolean = true
    
    Private mcabecera As Integer = 0
    
    Private msecuencia As Integer = 0
    
    Private msucursal As Integer = 0
    
    Private mrubro_contable As String = ""
    
    Private mdetalle_asiento As String = ""
    
    Private mdistribucion As String = ""
    
    Private mfecha_valor As String = ""
    
    Private mfuente_fondo As Integer = 0
    
    Private mcentro_costo As Integer = 0
    
    Private mdescripcion As String = ""
    
    Private msigno As String = ""
    
    Private mimporte As Double = 0
    
    Public Sub New()
        MyBase.New
    End Sub
    
    <XmlAttribute()>  _
    Public Overridable Property fecha_proceso() As String
        Get
            Return Me.mfecha_proceso
        End Get
        Set
            Me.mfecha_proceso = value
            EsModificado = true
        End Set
    End Property
    
    <XmlAttribute()>  _
    Public Overridable Property estado() As Boolean
        Get
            Return Me.mestado
        End Get
        Set
            Me.mestado = value
            EsModificado = true
        End Set
    End Property
    
    <XmlAttribute()>  _
    Public Overridable Property cabecera() As Integer
        Get
            Return Me.mcabecera
        End Get
        Set
            Me.mcabecera = value
            EsModificado = true
        End Set
    End Property
    
    <XmlAttribute()>  _
    Public Overridable Property secuencia() As Integer
        Get
            Return Me.msecuencia
        End Get
        Set
            Me.msecuencia = value
            EsModificado = true
        End Set
    End Property
    
    <XmlAttribute()>  _
    Public Overridable Property sucursal() As Integer
        Get
            Return Me.msucursal
        End Get
        Set
            Me.msucursal = value
            EsModificado = true
        End Set
    End Property
    
    <XmlAttribute()>  _
    Public Overridable Property rubro_contable() As String
        Get
            Return Me.mrubro_contable
        End Get
        Set
            Me.mrubro_contable = value
            EsModificado = true
        End Set
    End Property
    
    <XmlAttribute()>  _
    Public Overridable Property detalle_asiento() As String
        Get
            Return Me.mdetalle_asiento
        End Get
        Set
            Me.mdetalle_asiento = value
            EsModificado = true
        End Set
    End Property
    
    <XmlAttribute()>  _
    Public Overridable Property distribucion() As String
        Get
            Return Me.mdistribucion
        End Get
        Set
            Me.mdistribucion = value
            EsModificado = true
        End Set
    End Property
    
    <XmlAttribute()>  _
    Public Overridable Property fecha_valor() As String
        Get
            Return Me.mfecha_valor
        End Get
        Set
            Me.mfecha_valor = value
            EsModificado = true
        End Set
    End Property
    
    <XmlAttribute()>  _
    Public Overridable Property fuente_fondo() As Integer
        Get
            Return Me.mfuente_fondo
        End Get
        Set
            Me.mfuente_fondo = value
            EsModificado = true
        End Set
    End Property
    
    <XmlAttribute()>  _
    Public Overridable Property centro_costo() As Integer
        Get
            Return Me.mcentro_costo
        End Get
        Set
            Me.mcentro_costo = value
            EsModificado = true
        End Set
    End Property
    
    <XmlAttribute()>  _
    Public Overridable Property descripcion() As String
        Get
            Return Me.mdescripcion
        End Get
        Set
            Me.mdescripcion = value
            EsModificado = true
        End Set
    End Property
    
    <XmlAttribute()>  _
    Public Overridable Property signo() As String
        Get
            Return Me.msigno
        End Get
        Set
            Me.msigno = value
            EsModificado = true
        End Set
    End Property
    
    <XmlAttribute()>  _
    Public Overridable Property importe() As Double
        Get
            Return Me.mimporte
        End Get
        Set
            Me.mimporte = value
            EsModificado = true
        End Set
    End Property
End Class
#End Region
