'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión del motor en tiempo de ejecución:2.0.50727.5446
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports Infoware.Reglas
Imports System
Imports System.Xml
Imports System.Xml.Serialization


#Region "ParametroDet"
Partial Public Class ParametroDet
    Inherits _Database
    
    Private mParame_Codigo As Integer = 0
    
    Private mPardet_Secuencia As Integer = 0
    
    Private mPardet_Descripcion As String = ""
    
    Private mPardet_DatoStr1 As String = "('')"
    
    Private mPardet_DatoStr2 As String = "('')"
    
    Private mPardet_DatoStr3 As String = "('')"
    
    Private mPardet_DatoInt1 As Integer = "((0))"
    
    Private mPardet_Modificable As Boolean = "((1))"
    
    Private mParame_Padre As Integer = 0
    
    Private mPardet_Padre As Integer = 0
    
    Private mPardet_Imagen As String = ""
    
    Private mPardet_Leyenda As String = ""
    
    Private mCtaCtb_CtaCtble1 As String = ""
    
    Private mCtaCtb_CtaCtble2 As String = ""
    
    Private mPardet_DatoDec1 As Double = 0
    
    Private mPardet_DatoBit1 As Boolean = true
    
    Public Sub New()
        MyBase.New
    End Sub
    
    <XmlAttribute()>  _
    Public Overridable Property Parame_Codigo() As Integer
        Get
            Return Me.mParame_Codigo
        End Get
        Set
            Me.mParame_Codigo = value
            EsModificado = true
        End Set
    End Property
    
    <XmlAttribute()>  _
    Public Overridable Property Pardet_Secuencia() As Integer
        Get
            Return Me.mPardet_Secuencia
        End Get
        Set
            Me.mPardet_Secuencia = value
            EsModificado = true
        End Set
    End Property
    
    <XmlAttribute()>  _
    Public Overridable Property Pardet_Descripcion() As String
        Get
            Return Me.mPardet_Descripcion
        End Get
        Set
            Me.mPardet_Descripcion = value
            EsModificado = true
        End Set
    End Property
    
    <XmlAttribute()>  _
    Public Overridable Property Pardet_DatoStr1() As String
        Get
            Return Me.mPardet_DatoStr1
        End Get
        Set
            Me.mPardet_DatoStr1 = value
            EsModificado = true
        End Set
    End Property
    
    <XmlAttribute()>  _
    Public Overridable Property Pardet_DatoStr2() As String
        Get
            Return Me.mPardet_DatoStr2
        End Get
        Set
            Me.mPardet_DatoStr2 = value
            EsModificado = true
        End Set
    End Property
    
    <XmlAttribute()>  _
    Public Overridable Property Pardet_DatoStr3() As String
        Get
            Return Me.mPardet_DatoStr3
        End Get
        Set
            Me.mPardet_DatoStr3 = value
            EsModificado = true
        End Set
    End Property
    
    <XmlAttribute()>  _
    Public Overridable Property Pardet_DatoInt1() As Integer
        Get
            Return Me.mPardet_DatoInt1
        End Get
        Set
            Me.mPardet_DatoInt1 = value
            EsModificado = true
        End Set
    End Property
    
    <XmlAttribute()>  _
    Public Overridable Property Pardet_Modificable() As Boolean
        Get
            Return Me.mPardet_Modificable
        End Get
        Set
            Me.mPardet_Modificable = value
            EsModificado = true
        End Set
    End Property
    
    <XmlAttribute()>  _
    Public Overridable Property Parame_Padre() As Integer
        Get
            Return Me.mParame_Padre
        End Get
        Set
            Me.mParame_Padre = value
            EsModificado = true
        End Set
    End Property
    
    <XmlAttribute()>  _
    Public Overridable Property Pardet_Padre() As Integer
        Get
            Return Me.mPardet_Padre
        End Get
        Set
            Me.mPardet_Padre = value
            EsModificado = true
        End Set
    End Property
    
    <XmlAttribute()>  _
    Public Overridable Property Pardet_Imagen() As String
        Get
            Return Me.mPardet_Imagen
        End Get
        Set
            Me.mPardet_Imagen = value
            EsModificado = true
        End Set
    End Property
    
    <XmlAttribute()>  _
    Public Overridable Property Pardet_Leyenda() As String
        Get
            Return Me.mPardet_Leyenda
        End Get
        Set
            Me.mPardet_Leyenda = value
            EsModificado = true
        End Set
    End Property
    
    <XmlAttribute()>  _
    Public Overridable Property CtaCtb_CtaCtble1() As String
        Get
            Return Me.mCtaCtb_CtaCtble1
        End Get
        Set
            Me.mCtaCtb_CtaCtble1 = value
            EsModificado = true
        End Set
    End Property
    
    <XmlAttribute()>  _
    Public Overridable Property CtaCtb_CtaCtble2() As String
        Get
            Return Me.mCtaCtb_CtaCtble2
        End Get
        Set
            Me.mCtaCtb_CtaCtble2 = value
            EsModificado = true
        End Set
    End Property
    
    <XmlAttribute()>  _
    Public Overridable Property Pardet_DatoDec1() As Double
        Get
            Return Me.mPardet_DatoDec1
        End Get
        Set
            Me.mPardet_DatoDec1 = value
            EsModificado = true
        End Set
    End Property
    
    <XmlAttribute()>  _
    Public Overridable Property Pardet_DatoBit1() As Boolean
        Get
            Return Me.mPardet_DatoBit1
        End Get
        Set
            Me.mPardet_DatoBit1 = value
            EsModificado = true
        End Set
    End Property
End Class
#End Region
