'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión del motor en tiempo de ejecución:2.0.50727.5446
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports Infoware.Reglas
Imports System
Imports System.Xml
Imports System.Xml.Serialization


#Region "PolizaDet"
Partial Public Class PolizaDet
    Inherits _Database
    
    Private mPoliza_Codigo As Integer = 0
    
    Private mActivo_Codigo As Integer = 0
    
    Public Sub New()
        MyBase.New
    End Sub
    
    <XmlAttribute()>  _
    Public Overridable Property Poliza_Codigo() As Integer
        Get
            Return Me.mPoliza_Codigo
        End Get
        Set
            Me.mPoliza_Codigo = value
            EsModificado = true
        End Set
    End Property
    
    <XmlAttribute()>  _
    Public Overridable Property Activo_Codigo() As Integer
        Get
            Return Me.mActivo_Codigo
        End Get
        Set
            Me.mActivo_Codigo = value
            EsModificado = true
        End Set
    End Property
End Class
#End Region
