'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión del motor en tiempo de ejecución:2.0.50727.5446
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports Infoware.Reglas.Base
Imports System
Imports System.Xml
Imports System.Xml.Serialization


#Region "Restriccion"
Partial Public Class Restriccion
    Inherits _Database
    
    Private mUsuari_Codigo As String = ""
    
    Private mParame_Opciones As Integer = "((5))"
    
    Private mPardet_Opciones As Integer = 0
    
    Private mRestri_Lectura As Boolean = true
    
    Private mRestri_Ingreso As Boolean = true
    
    Private mRestri_Modificacion As Boolean = "((1))"
    
    Private mRestri_Eliminacion As Boolean = "((1))"
    
    Private mRestri_Impresion As Boolean = true
    
    Private mRestri_VerConfidencial As Boolean = true
    
    Private mRestri_Favorito As Boolean = "((0))"
    
    Public Sub New()
        MyBase.New
    End Sub
    
    <XmlAttribute()>  _
    Public Overridable Property Usuari_Codigo() As String
        Get
            Return Me.mUsuari_Codigo
        End Get
        Set
            Me.mUsuari_Codigo = value
            EsModificado = true
        End Set
    End Property
    
    <XmlAttribute()>  _
    Public Overridable Property Parame_Opciones() As Integer
        Get
            Return Me.mParame_Opciones
        End Get
        Set
            Me.mParame_Opciones = value
            EsModificado = true
        End Set
    End Property
    
    <XmlAttribute()>  _
    Public Overridable Property Pardet_Opciones() As Integer
        Get
            Return Me.mPardet_Opciones
        End Get
        Set
            Me.mPardet_Opciones = value
            EsModificado = true
        End Set
    End Property
    
    <XmlAttribute()>  _
    Public Overridable Property Restri_Lectura() As Boolean
        Get
            Return Me.mRestri_Lectura
        End Get
        Set
            Me.mRestri_Lectura = value
            EsModificado = true
        End Set
    End Property
    
    <XmlAttribute()>  _
    Public Overridable Property Restri_Ingreso() As Boolean
        Get
            Return Me.mRestri_Ingreso
        End Get
        Set
            Me.mRestri_Ingreso = value
            EsModificado = true
        End Set
    End Property
    
    <XmlAttribute()>  _
    Public Overridable Property Restri_Modificacion() As Boolean
        Get
            Return Me.mRestri_Modificacion
        End Get
        Set
            Me.mRestri_Modificacion = value
            EsModificado = true
        End Set
    End Property
    
    <XmlAttribute()>  _
    Public Overridable Property Restri_Eliminacion() As Boolean
        Get
            Return Me.mRestri_Eliminacion
        End Get
        Set
            Me.mRestri_Eliminacion = value
            EsModificado = true
        End Set
    End Property
    
    <XmlAttribute()>  _
    Public Overridable Property Restri_Impresion() As Boolean
        Get
            Return Me.mRestri_Impresion
        End Get
        Set
            Me.mRestri_Impresion = value
            EsModificado = true
        End Set
    End Property
    
    <XmlAttribute()>  _
    Public Overridable Property Restri_VerConfidencial() As Boolean
        Get
            Return Me.mRestri_VerConfidencial
        End Get
        Set
            Me.mRestri_VerConfidencial = value
            EsModificado = true
        End Set
    End Property
    
    <XmlAttribute()>  _
    Public Overridable Property Restri_Favorito() As Boolean
        Get
            Return Me.mRestri_Favorito
        End Get
        Set
            Me.mRestri_Favorito = value
            EsModificado = true
        End Set
    End Property
End Class
#End Region
