'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión del motor en tiempo de ejecución:2.0.50727.5446
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports Infoware.Reglas
Imports System
Imports System.Xml
Imports System.Xml.Serialization


#Region "Usuario"
Partial Public Class Usuario
    Inherits _Database
    
    Private mUsuari_Codigo As String = ""
    
    Private mUsuari_Descripcion As String = ""
    
    Private mUsuari_Password As Boolean = true
    
    Private mUsuari_Mensaje As String = ""
    
    Private mUsuari_RegEntSal As Boolean = true
    
    Private mUsuari_RegIngModEli As Boolean = true
    
    Private mUsuari_RegImp As Boolean = true
    
    Private mUsuari_RegConfidencial As Boolean = true
    
    Private mEntida_Empleado As Integer = 0
    
    Private mUsuari_CambiarContrasena As Boolean = "((0))"
    
    Private mUsuari_Activo As Boolean = "((1))"
    
    Private mParame_Ubicacion As Integer = 0
    
    Private mPardet_Ubicacion As Integer = 0
    
    Public Sub New()
        MyBase.New
    End Sub
    
    <XmlAttribute()>  _
    Public Overridable Property Usuari_Codigo() As String
        Get
            Return Me.mUsuari_Codigo
        End Get
        Set
            Me.mUsuari_Codigo = value
            EsModificado = true
        End Set
    End Property
    
    <XmlAttribute()>  _
    Public Overridable Property Usuari_Descripcion() As String
        Get
            Return Me.mUsuari_Descripcion
        End Get
        Set
            Me.mUsuari_Descripcion = value
            EsModificado = true
        End Set
    End Property
    
    <XmlAttribute()>  _
    Public Overridable Property Usuari_Password() As Boolean
        Get
            Return Me.mUsuari_Password
        End Get
        Set
            Me.mUsuari_Password = value
            EsModificado = true
        End Set
    End Property
    
    <XmlAttribute()>  _
    Public Overridable Property Usuari_Mensaje() As String
        Get
            Return Me.mUsuari_Mensaje
        End Get
        Set
            Me.mUsuari_Mensaje = value
            EsModificado = true
        End Set
    End Property
    
    <XmlAttribute()>  _
    Public Overridable Property Usuari_RegEntSal() As Boolean
        Get
            Return Me.mUsuari_RegEntSal
        End Get
        Set
            Me.mUsuari_RegEntSal = value
            EsModificado = true
        End Set
    End Property
    
    <XmlAttribute()>  _
    Public Overridable Property Usuari_RegIngModEli() As Boolean
        Get
            Return Me.mUsuari_RegIngModEli
        End Get
        Set
            Me.mUsuari_RegIngModEli = value
            EsModificado = true
        End Set
    End Property
    
    <XmlAttribute()>  _
    Public Overridable Property Usuari_RegImp() As Boolean
        Get
            Return Me.mUsuari_RegImp
        End Get
        Set
            Me.mUsuari_RegImp = value
            EsModificado = true
        End Set
    End Property
    
    <XmlAttribute()>  _
    Public Overridable Property Usuari_RegConfidencial() As Boolean
        Get
            Return Me.mUsuari_RegConfidencial
        End Get
        Set
            Me.mUsuari_RegConfidencial = value
            EsModificado = true
        End Set
    End Property
    
    <XmlAttribute()>  _
    Public Overridable Property Entida_Empleado() As Integer
        Get
            Return Me.mEntida_Empleado
        End Get
        Set
            Me.mEntida_Empleado = value
            EsModificado = true
        End Set
    End Property
    
    <XmlAttribute()>  _
    Public Overridable Property Usuari_CambiarContrasena() As Boolean
        Get
            Return Me.mUsuari_CambiarContrasena
        End Get
        Set
            Me.mUsuari_CambiarContrasena = value
            EsModificado = true
        End Set
    End Property
    
    <XmlAttribute()>  _
    Public Overridable Property Usuari_Activo() As Boolean
        Get
            Return Me.mUsuari_Activo
        End Get
        Set
            Me.mUsuari_Activo = value
            EsModificado = true
        End Set
    End Property
    
    <XmlAttribute()>  _
    Public Overridable Property Parame_Ubicacion() As Integer
        Get
            Return Me.mParame_Ubicacion
        End Get
        Set
            Me.mParame_Ubicacion = value
            EsModificado = true
        End Set
    End Property
    
    <XmlAttribute()>  _
    Public Overridable Property Pardet_Ubicacion() As Integer
        Get
            Return Me.mPardet_Ubicacion
        End Get
        Set
            Me.mPardet_Ubicacion = value
            EsModificado = true
        End Set
    End Property
End Class
#End Region
