'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión del motor en tiempo de ejecución:2.0.50727.5446
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports Infoware.Datos


#Region "ActivoUbicacion"
Public Class ActivoUbicacion
    
    Const _Procedimiento As String = "proc_ActivoUbicacion"
    
    Private mActivo As Activo = Nothing

  Private mPardetUbicacion As WWTSParametroDet = Nothing

  Private mTransaccionActivo As TransaccionActivo = Nothing

    Public Sub New(ByVal _OperadorDatos As OperadorDatos, ByVal _EsNuevo As Boolean)
        MyBase.New
        OperadorDatos = _OperadorDatos
        EsNuevo = _EsNuevo
    End Sub
    
    Public Sub New(ByVal _OperadorDatos As OperadorDatos, ByVal _Activo_Codigo As Integer, ByVal _ActUbi_Secuencia As Integer)
        Me.New(_OperadorDatos, false)
        Activo_Codigo = _Activo_Codigo
        ActUbi_Secuencia = _ActUbi_Secuencia
        If Me.Recargar Then
        Else
            Throw New System.Exception("No se puede cargar objeto ActivoUbicacion")
        End If
    End Sub
    
  'Activo
  Public Overridable Property Activo() As Activo
    Get
      If mActivo Is Nothing AndAlso Activo_Codigo > 0 Then
        mActivo = New Activo(OperadorDatos, Activo_Codigo)
      End If
      Return Me.mActivo
    End Get
    Set(value As Activo)
      Me.mActivo = value
      Activo_Codigo = value.Activo_Codigo
    End Set
  End Property

  'Parametrodet
  Public Overridable Overloads Property PardetUbicacion() As WWTSParametroDet
    Get
      If mPardetUbicacion Is Nothing AndAlso Pardet_Ubicacion > 0 Then
        mPardetUbicacion = New WWTSParametroDet(OperadorDatos, Parame_Ubicacion, Pardet_Ubicacion)
      End If
      Return Me.mPardetUbicacion
    End Get
    Set(value As WWTSParametroDet)
      Me.mPardetUbicacion = value
      Parame_Ubicacion = value.Parame_Codigo
      Pardet_Ubicacion = value.Pardet_Secuencia
    End Set
  End Property

  'TransaccionActivo
  Public Overridable Property TransaccionActivo() As TransaccionActivo
    Get
      If mTransaccionActivo Is Nothing AndAlso mTransa_Codigo > 0 Then
        mTransaccionActivo = New TransaccionActivo(OperadorDatos, mTransa_Codigo)
      End If
      Return Me.mTransaccionActivo
    End Get
    Set(value As TransaccionActivo)
      Me.mTransaccionActivo = value
      If value Is Nothing Then
        mTransa_Codigo = 0
      Else
        mTransa_Codigo = value.Transa_Codigo
      End If
    End Set
  End Property

  <Infoware.Reportes.CampoReporteAtributo("Estado", Infoware.Reportes.CampoReporteAtributo.EnumTipoDato.Logico, 45, True)> _
  Public ReadOnly Property esActivo() As Boolean
    Get
      Return ActUbi_Activo
    End Get
  End Property

  <Infoware.Reportes.CampoReporteAtributo("Activo", Infoware.Reportes.CampoReporteAtributo.EnumTipoDato.Texto, 250, True)> _
  Public ReadOnly Property ActivoString() As String
    Get
      If Activo Is Nothing Then
        Return String.Empty
      Else
        Return Activo.Descripcion
      End If
    End Get
  End Property

  <Infoware.Reportes.CampoReporteAtributo("Ubicación", Infoware.Reportes.CampoReporteAtributo.EnumTipoDato.Texto, 350, True)> _
  Public ReadOnly Property UbicacionString() As String
    Get
      If PardetUbicacion Is Nothing Then
        Return String.Empty
      Else
        Return PardetUbicacion.DescripcionLarga
      End If
    End Get
  End Property

  <Infoware.Reportes.CampoReporteAtributo("Desde", Infoware.Reportes.CampoReporteAtributo.EnumTipoDato.Texto, 100, True)> _
  Public ReadOnly Property DesdeString() As String
    Get
      Return ActUbi_FechaDesde.ToShortDateString
    End Get
  End Property

  <Infoware.Reportes.CampoReporteAtributo("Hasta", Infoware.Reportes.CampoReporteAtributo.EnumTipoDato.Texto, 100, True)> _
  Public ReadOnly Property HastaString() As String
    Get
      If ActUbi_FechaHasta = Nothing Then
        Return String.Empty
      Else
        Return ActUbi_FechaHasta.ToShortDateString
      End If
    End Get
  End Property

  Public Overridable Sub MapearDataRowaObjeto(ByVal Fila As DataRow)
    Activo_Codigo = CType(Fila("Activo_Codigo"), Integer)
    ActUbi_Secuencia = CType(Fila("ActUbi_Secuencia"), Integer)
    ActUbi_Activo = CType(Fila("ActUbi_Activo"), Boolean)
    Parame_Ubicacion = CType(Fila("Parame_Ubicacion"), Integer)
    Pardet_Ubicacion = CType(Fila("Pardet_Ubicacion"), Integer)
    ActUbi_FechaDesde = CDate(Fila("ActUbi_FechaDesde"))
    If TypeOf Fila("ActUbi_FechaHasta") Is dbnull Then
      ActUbi_FechaHasta = Nothing
    Else
      ActUbi_FechaHasta = CDate(Fila("ActUbi_FechaHasta"))
    End If
    If TypeOf Fila("Transa_Codigo") Is DBNull Then
      Transa_Codigo = 0
    Else
      Transa_Codigo = CInt(Fila("Transa_Codigo"))
    End If

    mActivo = Nothing
    mPardetUbicacion = Nothing
  End Sub
    
    Public Overridable Function Recargar() As Boolean
        Dim Result As System.Data.DataTable = New System.Data.DataTable
        Dim bReturn As Boolean = true
        OperadorDatos.AgregarParametro("@accion", "C")
        OperadorDatos.AgregarParametro("@Activo_Codigo", Activo_Codigo)
        OperadorDatos.AgregarParametro("@ActUbi_Secuencia", ActUbi_Secuencia)
        OperadorDatos.Procedimiento = _Procedimiento
        bReturn = OperadorDatos.Ejecutar(Result)
        OperadorDatos.LimpiarParametros
        Try 
      Me.MapearDataRowaObjeto(Result.Rows(0))
            EsNuevo = false
            EsModificado = false
        Catch ex As System.Exception
            bReturn = false
        End Try
        Return bReturn
    End Function
    
  Public Overridable Function Guardar() As Boolean
    Dim Result As Integer = 0
    Dim bReturn As Boolean = True
    Dim sAccion As String = "M"
    If EsNuevo Then
      sAccion = "I"
    End If
    OperadorDatos.AgregarParametro("@accion", sAccion)
    OperadorDatos.AgregarParametro("@Activo_Codigo", Activo_Codigo)
    OperadorDatos.AgregarParametro("@ActUbi_Secuencia", ActUbi_Secuencia)
    OperadorDatos.AgregarParametro("@ActUbi_Activo", ActUbi_Activo)
    OperadorDatos.AgregarParametro("@Parame_Ubicacion", Parame_Ubicacion)
    OperadorDatos.AgregarParametro("@Pardet_Ubicacion", Pardet_Ubicacion)
    OperadorDatos.AgregarParametro("@ActUbi_FechaDesde", ActUbi_FechaDesde)
    If Not ActUbi_FechaHasta = Nothing Then
      OperadorDatos.AgregarParametro("@ActUbi_FechaHasta", ActUbi_FechaHasta)
    End If
    If Transa_Codigo > 0 Then
      OperadorDatos.AgregarParametro("@Transa_Codigo", Transa_Codigo)
    End If
    OperadorDatos.Procedimiento = _Procedimiento
    bReturn = OperadorDatos.Ejecutar(Result)
    OperadorDatos.LimpiarParametros()
    If bReturn Then
      If EsNuevo Then
        ActUbi_Secuencia = Result
      End If

      If Not OperadorDatos.EstaenTransaccion Then
        Me.AceptarCambios()
      End If
    End If
    Return bReturn
  End Function
    
    Public Overridable Sub AceptarCambios()
        EsNuevo = false
        EsModificado = false
    End Sub
    
    Public Overridable Function Eliminar() As Boolean
        Dim bReturn As Boolean = true
        OperadorDatos.AgregarParametro("@accion", "E")
        OperadorDatos.AgregarParametro("@Activo_Codigo", Activo_Codigo)
        OperadorDatos.AgregarParametro("@ActUbi_Secuencia", ActUbi_Secuencia)
        OperadorDatos.Procedimiento = _Procedimiento
        bReturn = OperadorDatos.Ejecutar
        OperadorDatos.LimpiarParametros
        Return bReturn
    End Function
End Class
#End Region

#Region "ActivoUbicacionList"
Public Class ActivoUbicacionList
  Inherits System.ComponentModel.BindingList(Of ActivoUbicacion)

  Public Shared Function ObtenerLista(ByVal _Activo As Activo, Optional ByVal _filtro As String = "") As ActivoUbicacionList
    Dim oResult As New ActivoUbicacionList
    Dim bReturn As Boolean
    Dim ds As DataTable = Nothing
    With _Activo.OperadorDatos
      .AgregarParametro("@Accion", "F")
      .AgregarParametro("@Activo_Codigo", _Activo.Activo_Codigo)
      .AgregarParametro("@filtro", _filtro)
      .Procedimiento = "proc_ActivoUbicacion"
      bReturn = .Ejecutar(ds)
      .LimpiarParametros()
    End With
    If bReturn AndAlso Not ds Is Nothing AndAlso ds.Rows.Count > 0 Then
      For Each _dr As DataRow In ds.Rows
        Dim _fila As New ActivoUbicacion(_Activo.OperadorDatos, False)
        _fila.MapearDataRowaObjeto(_dr)
        oResult.Add(_fila)
      Next
    End If
    Return oResult
  End Function

  Public Shared Function ObtenerLista(ByVal _TransaccionActivo As TransaccionActivo, Optional ByVal _filtro As String = "") As ActivoUbicacionList
    Dim oResult As New ActivoUbicacionList
    Dim bReturn As Boolean
    Dim ds As DataTable = Nothing
    With _TransaccionActivo.OperadorDatos
      .AgregarParametro("@Accion", "FT")
      .AgregarParametro("@Transa_Codigo", _TransaccionActivo.Transa_Codigo)
      .AgregarParametro("@filtro", _filtro)
      .Procedimiento = "proc_ActivoUbicacion"
      bReturn = .Ejecutar(ds)
      .LimpiarParametros()
    End With
    If bReturn AndAlso Not ds Is Nothing AndAlso ds.Rows.Count > 0 Then
      For Each _dr As DataRow In ds.Rows
        Dim _fila As New ActivoUbicacion(_TransaccionActivo.OperadorDatos, False)
        _fila.MapearDataRowaObjeto(_dr)
        oResult.Add(_fila)
      Next
    End If
    Return oResult
  End Function

  Public Shared Function ObtenerActivos(ByVal _Activo As Activo, Optional ByVal _filtro As String = "") As ActivoUbicacionList
    Dim oResult As New ActivoUbicacionList
    Dim bReturn As Boolean
    Dim ds As DataTable = Nothing
    With _Activo.OperadorDatos
      .AgregarParametro("@Accion", "Fa")
      .AgregarParametro("@Activo_Codigo", _Activo.Activo_Codigo)
      .AgregarParametro("@filtro", _filtro)
      .Procedimiento = "proc_ActivoUbicacion"
      bReturn = .Ejecutar(ds)
      .LimpiarParametros()
    End With
    If bReturn AndAlso Not ds Is Nothing AndAlso ds.Rows.Count > 0 Then
      For Each _dr As DataRow In ds.Rows
        Dim _fila As New ActivoUbicacion(_Activo.OperadorDatos, False)
        _fila.MapearDataRowaObjeto(_dr)
        oResult.Add(_fila)
      Next
    End If
    Return oResult
  End Function

End Class
#End Region
