'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión del motor en tiempo de ejecución:2.0.50727.5446
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports Infoware.Datos


#Region "sysdiagrams"
Public Class sysdiagrams
    
    Const _Procedimiento As String = "proc_sysdiagrams"
    
    Public Sub New(ByVal _OperadorDatos As OperadorDatos, ByVal _EsNuevo As Boolean)
        MyBase.New
        OperadorDatos = _OperadorDatos
        EsNuevo = _EsNuevo
    End Sub
    
    Public Sub New(ByVal _OperadorDatos As OperadorDatos, ByVal _diagram_id As Integer)
        Me.New(_OperadorDatos, false)
        diagram_id = _diagram_id
        If Me.Recargar Then
        Else
            Throw New System.Exception("No se puede cargar objeto sysdiagrams")
        End If
    End Sub
    
    Public Overridable Sub MapearDataRowaObjeto(ByVal Fila As DataRow)
        name = CType(Fila("name"),String)
        principal_id = CType(Fila("principal_id"),Integer)
        diagram_id = CType(Fila("diagram_id"),Integer)
        version = CType(Fila("version"),Integer)
        definition = CType(Fila("definition"),Boolean)
    End Sub
    
    Public Overridable Function Recargar() As Boolean
        Dim Result As System.Data.DataTable = New System.Data.DataTable
        Dim bReturn As Boolean = true
        OperadorDatos.AgregarParametro("@accion", "C")
        OperadorDatos.AgregarParametro("@diagram_id", diagram_id)
        OperadorDatos.Procedimiento = _Procedimiento
        bReturn = OperadorDatos.Ejecutar(Result)
        OperadorDatos.LimpiarParametros
        Try 
      Me.MapearDataRowaObjeto(Result.Rows(0))
            EsNuevo = false
            EsModificado = false
        Catch ex As System.Exception
            bReturn = false
        End Try
        Return bReturn
    End Function
    
    Public Overridable Function Guardar() As Boolean
        Dim Result As Integer = 0
        Dim bReturn As Boolean = true
        Dim sAccion As String = "M"
        If esNuevo Then
            sAccion = "I"
        End If
        OperadorDatos.AgregarParametro("@accion", sAccion)
        OperadorDatos.AgregarParametro("@name", name)
        OperadorDatos.AgregarParametro("@principal_id", principal_id)
        OperadorDatos.AgregarParametro("@diagram_id", diagram_id)
        OperadorDatos.AgregarParametro("@version", version)
        OperadorDatos.AgregarParametro("@definition", definition)
        OperadorDatos.Procedimiento = _Procedimiento
        bReturn = OperadorDatos.Ejecutar(Result)
        OperadorDatos.LimpiarParametros
        If bReturn Then
            If OperadorDatos.EstaenTransaccion Then
            Else
                Me.AceptarCambios
            End If
        End If
        Return bReturn
    End Function
    
    Public Overridable Sub AceptarCambios()
        EsNuevo = false
        EsModificado = false
    End Sub
    
    Public Overridable Function Eliminar() As Boolean
        Dim bReturn As Boolean = true
        OperadorDatos.AgregarParametro("@accion", "E")
        OperadorDatos.AgregarParametro("@diagram_id", diagram_id)
        OperadorDatos.Procedimiento = _Procedimiento
        bReturn = OperadorDatos.Ejecutar
        OperadorDatos.LimpiarParametros
        Return bReturn
    End Function
End Class
#End Region

#Region "sysdiagramsList"
Public Class sysdiagramsList
    Inherits System.ComponentModel.BindingList(Of )
End Class
#End Region
