'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión del motor en tiempo de ejecución:2.0.50727.5446
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports Infoware.Datos


#Region "Usuario"
Public Class Usuario
    
    Const _Procedimiento As String = "proc_Usuario"
    
    Public Sub New(ByVal _OperadorDatos As OperadorDatos, ByVal _EsNuevo As Boolean)
        MyBase.New
        OperadorDatos = _OperadorDatos
        EsNuevo = _EsNuevo
    End Sub
    
    Public Sub New(ByVal _OperadorDatos As OperadorDatos, ByVal _Usuari_Codigo As String)
        Me.New(_OperadorDatos, false)
        Usuari_Codigo = _Usuari_Codigo
        If Me.Recargar Then
        Else
            Throw New System.Exception("No se puede cargar objeto Usuario")
        End If
    End Sub
    
    Public Overridable Sub MapearDataRowaObjeto(ByVal Fila As DataRow)
        Usuari_Codigo = CType(Fila("Usuari_Codigo"),String)
        Usuari_Descripcion = CType(Fila("Usuari_Descripcion"),String)
        Usuari_Password = CType(Fila("Usuari_Password"),Boolean)
        Usuari_Mensaje = CType(Fila("Usuari_Mensaje"),String)
        Usuari_RegEntSal = CType(Fila("Usuari_RegEntSal"),Boolean)
        Usuari_RegIngModEli = CType(Fila("Usuari_RegIngModEli"),Boolean)
        Usuari_RegImp = CType(Fila("Usuari_RegImp"),Boolean)
        Usuari_RegConfidencial = CType(Fila("Usuari_RegConfidencial"),Boolean)
        Entida_Empleado = CType(Fila("Entida_Empleado"),Integer)
        Usuari_CambiarContrasena = CType(Fila("Usuari_CambiarContrasena"),Boolean)
        Usuari_Activo = CType(Fila("Usuari_Activo"),Boolean)
        Parame_Ubicacion = CType(Fila("Parame_Ubicacion"),Integer)
        Pardet_Ubicacion = CType(Fila("Pardet_Ubicacion"),Integer)
    End Sub
    
    Public Overridable Function Recargar() As Boolean
        Dim Result As System.Data.DataTable = New System.Data.DataTable
        Dim bReturn As Boolean = true
        OperadorDatos.AgregarParametro("@accion", "C")
        OperadorDatos.AgregarParametro("@Usuari_Codigo", Usuari_Codigo)
        OperadorDatos.Procedimiento = _Procedimiento
        bReturn = OperadorDatos.Ejecutar(Result)
        OperadorDatos.LimpiarParametros
        Try 
      Me.MapearDataRowaObjeto(Result.Rows(0))
            EsNuevo = false
            EsModificado = false
        Catch ex As System.Exception
            bReturn = false
        End Try
        Return bReturn
    End Function
    
    Public Overridable Function Guardar() As Boolean
        Dim Result As Integer = 0
        Dim bReturn As Boolean = true
        Dim sAccion As String = "M"
        If esNuevo Then
            sAccion = "I"
        End If
        OperadorDatos.AgregarParametro("@accion", sAccion)
        OperadorDatos.AgregarParametro("@Usuari_Codigo", Usuari_Codigo)
        OperadorDatos.AgregarParametro("@Usuari_Descripcion", Usuari_Descripcion)
        OperadorDatos.AgregarParametro("@Usuari_Password", Usuari_Password)
        OperadorDatos.AgregarParametro("@Usuari_Mensaje", Usuari_Mensaje)
        OperadorDatos.AgregarParametro("@Usuari_RegEntSal", Usuari_RegEntSal)
        OperadorDatos.AgregarParametro("@Usuari_RegIngModEli", Usuari_RegIngModEli)
        OperadorDatos.AgregarParametro("@Usuari_RegImp", Usuari_RegImp)
        OperadorDatos.AgregarParametro("@Usuari_RegConfidencial", Usuari_RegConfidencial)
        OperadorDatos.AgregarParametro("@Entida_Empleado", Entida_Empleado)
        OperadorDatos.AgregarParametro("@Usuari_CambiarContrasena", Usuari_CambiarContrasena)
        OperadorDatos.AgregarParametro("@Usuari_Activo", Usuari_Activo)
        OperadorDatos.AgregarParametro("@Parame_Ubicacion", Parame_Ubicacion)
        OperadorDatos.AgregarParametro("@Pardet_Ubicacion", Pardet_Ubicacion)
        OperadorDatos.Procedimiento = _Procedimiento
        bReturn = OperadorDatos.Ejecutar(Result)
        OperadorDatos.LimpiarParametros
        If bReturn Then
            If OperadorDatos.EstaenTransaccion Then
            Else
                Me.AceptarCambios
            End If
        End If
        Return bReturn
    End Function
    
    Public Overridable Sub AceptarCambios()
        EsNuevo = false
        EsModificado = false
    End Sub
    
    Public Overridable Function Eliminar() As Boolean
        Dim bReturn As Boolean = true
        OperadorDatos.AgregarParametro("@accion", "E")
        OperadorDatos.AgregarParametro("@Usuari_Codigo", Usuari_Codigo)
        OperadorDatos.Procedimiento = _Procedimiento
        bReturn = OperadorDatos.Ejecutar
        OperadorDatos.LimpiarParametros
        Return bReturn
    End Function
End Class
#End Region

#Region "UsuarioList"
Public Class UsuarioList
    Inherits System.ComponentModel.BindingList(Of )
End Class
#End Region
